#!/bin/bash



# UPDATE CONFIG FILE

#get variables from user.conf
clear
source user.conf || {
	echo "Unable to access to conf/user.conf."
	echo -e "\n[Starting cancelled]"
	exit 1
}



# STOP SERVER

#disable site on apache2
a2dissite $serverName.conf && {
	echo    "Successfully disabled server on apache."
	echo -e "\nServer $serverName is OFFLINE."
} || {
	echo -e "\nCould not disable server on apache2."
	echo -e "\n[Stopping cancelled]"
	exit 1
}
