#!/bin/bash



# UPDATE CONFIG FILE

#root user
clear
if [[ $USER != 'root' ]]; then
	echo "This program must be launched as root."
	echo -e "\n[Stopping cancelled]"
	exit 1
fi

#get variables from user.conf
clear
source conf/user.conf || {
	echo "Unable to access to conf/user.conf."
	echo -e "\n[Stopping cancelled]"
	exit 1
}



# STOP SERVER

#disable site on apache2
a2dissite $serverName.conf && \
systemctl restart apache2  && {
	echo -e "\nSuccessfully disabled server on apache."
	echo -e "\nServer $serverName is OFFLINE."
} || {
	echo -e "\nCould not disable server on apache2."
	echo -e "\n[Stopping cancelled]"
	exit 1
}
